CREATE SCHEMA AIRPORT_MANAGEMENT_SYSTEM;
USE AIRPORT_MANAGEMENT_SYSTEM;

CREATE TABLE PASSENGERS
(
    ID    INT AUTO_INCREMENT PRIMARY KEY,
    NAME  VARCHAR(100) NOT NULL,
    PHONE VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE ADDRESS
(
    ID      INT AUTO_INCREMENT PRIMARY KEY,
    COUNTRY VARCHAR(100) UNIQUE,
    CITY    VARCHAR(100)
);
CREATE TABLE COMPANIES
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    FOUND_DATE DATE,
    ADDRESS_ID INT,
    CONSTRAINT `FK` FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID)
        ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE TRIP
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    COMPANY_ID INT,
    TIME_IN    DATE,
    TIME_OUT   DATE,
    CITY_FROM  VARCHAR(100),
    CITY_TOO   VARCHAR(100),
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES (ID) ON UPDATE CASCADE
);
CREATE TABLE PASSENGER_TRIPS
(
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    PASSENGER_ID INT,
    TRIP_ID      INT,
    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGERS (ID) ON UPDATE CASCADE,
    FOREIGN KEY (TRIP_ID) REFERENCES TRIP (ID) ON UPDATE CASCADE
);